---
name: Echo Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Hello, DevOps!"
      - name: Multi line step
        run: |
          pwd
      - name: Display GitHub Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
      - name: Use Variables
        run: |
          echo "Variable: ${{ vars.MY_VARIABLE }}"
